language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
  - "pypy3"
# tcl8.5/tk8.5 is required for pillow + pypy
before_install:
  - sudo add-apt-repository --yes ppa:malept/$OATH_PPA
  - sudo apt-get update -qq
  - sudo apt-get install -qq liboath0
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]] && [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then sudo apt-get install -qq liboath-dev; fi;
install:
  - PYPACKAGES="cffi"; if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then PYPACKAGES="$PYPACKAGES Cython"; fi; if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then PYPACKAGES="$PYPACKAGES ordereddict unittest2 Django<1.7 django-otp"; else PYPACKAGES="$PYPACKAGES -r requirements/django-otp.txt"; fi; pip install -r requirements/test.txt -r examples/oathtool/requirements.txt $PYPACKAGES; pip install .
script:
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then python setup.py check --metadata --restructuredtext --strict; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then export PYTHONDONTWRITEBYTECODE=1; fi; ./tests/run_tests.py --verbose
  - ./examples/oathtool/run_tests.sh
env:
  matrix:
    - OATH_PPA=oath-toolkit
    - OATH_PPA=oath-toolkit-2
matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.4"
